### ISSUE TITLE
StixIoc server 404

### ISSUE THREAD

**Issue by fawz24** [JPCERTCC/SysmonSearch#2]
After following the steps as mentioned in the wiki 

> https://github.com/JPCERTCC/SysmonSearch/wiki/how-to-install#stixioc-server-setup

I run up to the following response from the StixIoc server (on both Windows 7 x64 and Ubuntu 18.04 x64)

> Traceback (most recent call last):
  File "/home/ubuntu1804/Documents/elk/SysmonSearch/stixioc-import-server/.env/local/lib/python2.7/site-packages/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/home/ubuntu1804/Documents/elk/SysmonSearch/stixioc-import-server/.env/local/lib/python2.7/site-packages/tornado/web.py", line 2322, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

I couldn't figure out what's going on.
Any support is welcomed.

**Comment by PinGMUICT** [comment]
Same issue

**Comment by mrwhoo** [comment]
Same problem

**Comment by S03D4-164** [comment]
Sorry for the late reply.

The stixioc-import-server returns error except for the POST to the following paths:
- /convert/stix/v1
- /convert/stix/v2
- /convert/ioc

You can check the server's response by executing the following command in stixioc-import-server directory:
<pre>
# If running in the localhost:
$ curl localhost:56020/convert/ioc -F 'file=@data/sample.ioc.xml'
</pre>
